# Generated by Django 5.1.1 on 2025-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('subject_file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Student_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Class',
            field=models.CharField(choices=[('None', 'None'), ('class1', 'class1'), ('class2', 'class2'), ('class3', 'class3'), ('class4', 'class4'), ('class5', 'class5'), ('class6', 'class6'), ('form1', 'form1'), ('form2', 'form2'), ('form3', 'form3')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'student'), ('Teacher', 'teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='UploadRecordFile',
        ),
    ]
