# Generated by Django 5.1.1 on 2025-05-26 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0002_uploadresult_remove_customuser_student_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('file', models.FileField(default=None, upload_to='excel_file')),
            ],
        ),
        migrations.DeleteModel(
            name='Assess_Student',
        ),
        migrations.DeleteModel(
            name='studentLogin',
        ),
        migrations.DeleteModel(
            name='studentResult',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
        migrations.AddField(
            model_name='uploadrecordfile',
            name='FormMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
