# Generated by Django 5.1.1 on 2025-05-26 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0003_uploadrecordfile_delete_assess_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecordfile',
            name='FormMaster',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='record_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
