# Generated by Django 5.1.1 on 2025-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0004_alter_uploadrecordfile_formmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
