# Generated by Django 5.1.1 on 2025-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='role',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
